// src/app/resume/resume.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-resume',
  templateUrl: './resume.component.html',
  styleUrls: ['./resume.component.css']
})
export class ResumeComponent implements OnInit {

  displayWorkDetails1 = false;
  displayWorkDetails2 = false;
  displayWorkDetails3 = false;
  displayWorkDetails4 = false;

  constructor() { }

  ngOnInit() {
    this.displayWorkDetails1 = true;
  }
  showWorkDetails1() {
   this.displayWorkDetails1 = true;
   this.displayWorkDetails2 = false;
   this.displayWorkDetails3 = false;
   this.displayWorkDetails4 = false;
  }
  showWorkDetails2() {
   this.displayWorkDetails1 = false;
   this.displayWorkDetails2 = true;
   this.displayWorkDetails3 = false;
   this.displayWorkDetails4 = false;
  }
  showWorkDetails3() {
   this.displayWorkDetails1 = false;
   this.displayWorkDetails2 = false;
   this.displayWorkDetails3 = true;
   this.displayWorkDetails4 = false;
  }
  showWorkDetails4() {
   this.displayWorkDetails1 = false;
   this.displayWorkDetails2 = false;
   this.displayWorkDetails3 = false;
   this.displayWorkDetails4 = true;
  }
}


<section class="slide-top">
    <div class="wrap">
    <div class="card-70">
      <div class="content-left">
        <h1>Core Competencies</h1>
      </div>
    </div>
  </div>
  <div class="wrap">
    <div class="card-70">
      <div class="content-left">
        <h4>Significant Experience</h4>
        <ul class="description">
          <li>HTML5 / CSS3</li>
          <li>JavaScript</li>
          <li>Angular</li>
          <li>Node.js</li>
          <li>jQuery</li>
          <li>RESTful APIs</li>
          <li>SQL</li>
          <li>Linux / UNIX commands</li>
          <li>Bootstrap / Material / Responsive Design</li>
          <li>Sass / LESS</li>
          <li>GIT / SVN</li>
          <li>Agile / Lean / Kanban Process</li>
        </ul>
      </div> 
      <div class="content-left">
        <h4>Knowledgeable / Learning</h4>
        <ul class="description">
          <li>Ionic</li>
          <li>React</li>
          <li>Vue.js</li>
          <li>Knockout</li>
          <li>Python</li>
          <li>Java</li>
          <li>Amazon Web Services</li>
          <li>WordPress / PHP</li>
          <li>Ruby on Rails</li>
        </ul>
      </div>
    </div>      
  </div>
  <hr>
  <div class="wrap">
    <div class="card-70">
      <div class="content-left">
        <h1>Work Experience</h1>
        <ul class="flexblock specs">
          <h4>Pariveda Solutions - Dallas, TX</h4>
          <li (click)="showWorkDetails1()">
            <a title="Consultant">
              <div>
                <h2>Consultant</h2>
                <p class="year">
                  July 2018 - present
                </p>
              </div>
            </a>
          </li>
          <h4>Nucor Corporation - Dallas, TX</h4>
          <li (click)="showWorkDetails2()">
            <a title="Oracle SOA Developer">
              <div>
                <h2>Oracle SOA Developer</h2>
                <p class="year">
                  October 2015 – June 2018
                </p>
              </div>
            </a>
          </li>
          <h4>Nucor-Yamato Steel - Blytheville, AR</h4>
          <li (click)="showWorkDetails3()">
            <a title="IT Business Process Analyst">
              <h2>IT Business Process Analyst</h2>
              <p class="year">
                December 2014 – October 2015
              </p>
            </a>
          </li>
          <li (click)="showWorkDetails4()">
            <a title="IT Systems Analyst">
              <h2>IT Systems Analyst</h2>
              <p class="year">
                May 2014 – December 2014
              </p>
            </a>
          </li>
          <li (click)="showWorkDetails5()">
            <a title="IT Intern">
              <h2>IT Intern</h2>
              <p class="year">
                January 2013 – July 2013
              </p> 
            </a>
          </li>
        </ul>
      </div>
      <!-- end .flex-content-->
      <figure>
          <div *ngIf="displayWorkDetails1">
            <h3>Consultant</h3>
            <p>• Utilized Agile methodologies along with a streamlined devops cycle to rapidly provide high-value enhancements post go-
              live of an enterprise level custom web application.
            </p>
            <p>• Contributed to a team tasked with developing new features one of which was a scheduling module that was valued to
              have over a $1,000,000 per year return on investment.
            </p>
            <p>• Efficiently and effectively collaborated with many different teams such as business analysts, quality assurance, and
              subject matter experts to ensure the highest quality product was delivered.
            </p>
            <p>• Utilized JIRA significantly to improve Agile performance during which I improved my abilities to estimate development
              tasks and deliver on or ahead of schedule.
            </p>
            <p>• Frequently presented to the team during code reviews, lunch and learns, and post sprint retrospectives.</p>
          </div>
        <div *ngIf="displayWorkDetails2">
          <h3>Oracle SOA Developer Details</h3>
          <p>• Designed, developed and maintained a mobile optimized web application using the latest technologies such as Angular with TypeScript, HTML5, CSS3, Sass, Material Design and JSON RESTful APIs.</p>
          <p>• Used tools such as Jenkins for automated deployments and Subversion for version control.</p>
          <p>• Extensively used UNIX based server architecture and became very familiar with UNIX commands.</p>
          <p>• Responsible for secured file transmissions to and from multiple bank trading partners using FTPS with SSL certificates as well as SFTP and SSH key authentication.</p>
          <p>• Gathered business requirements from subject matter experts and end users to determine robust, technical solutions to meet those requirements within Oracle E-Business Suite (EBS).</p>
          <p>• Exercised principles of the software development lifecycle (SDLC) with a large, diverse development team to ensure software applications were delivered within project scope, budget and timeline.</p>
          <p>• Evaluated Oracle MFT as solution and then implemented from concept to completion.</p>
          <p>• Developed SOA composite applications using Oracle JDeveloper to integrate external systems into Oracle EBS.</p> 
        </div>
        <div *ngIf="displayWorkDetails3">
          <h3>IT Business Process Analyst Details</h3>
          <p>• Coordinated directly with internal and external consultants as well as main implementer for maintaining and implementing existing and future modules of Oracle E-Business Suite.</p>
          <p>• Assisted in transition legacy IBM AS400 system to Oracle EBS.</p>
          <p>• Developed reports from Oracle using an ad-hoc reporting solution from EiS Technologies.</p>
        </div>
        <div *ngIf="displayWorkDetails4">
          <h3>IT Systems Analyst Details</h3>
          <p>• Responsible for making a real time copy of various data sources and types and then used Informatica for ETL and then stored data into a data warehouse to improve corporate level reporting.</p>
          <p>• Administered and maintained a vSphere environment with more than 150 virtual servers.</p>
          <p>• Implemented and administered a VMware Horizon View environment that contained more than 50 virtual desktops.</p>
        </div>
        <div *ngIf="displayWorkDetails5">
          <h3>IT Intern Details</h3>
          <p>• Configured PCs, VOIP phones, iPhones and other devices for deployment to various users.</p>
          <p>• Diagnosed and corrected various computer and network problems.</p>
          <p>• Responsible for the IT needs of two newly constructed buildings, such as configuring network switches, terminating fiber optic and Ethernet cable, purchasing and configuring PCs, VOIP phones, and printers.</p>
        </div>
      </figure>
    </div>
    <!-- .end card-50 -->
  </div>
  <hr>
  <div class="wrap">
    <div class="card-50">
      <div class="content-left">
      <!-- <div class="flex-content"> -->
        <h1>Education</h1>
        <h4>Missouri University of Science & Technology</h4>
        <ul class="flexblock">
          <li>
            <a title="Information Science & Technology">
              <div>
                <h2>B.S. Information Science & Technology</h2>
                <div>Minor: Enterprise Resource Planning</div>
                <div>Minor: Business & Management Systems</div>
                <p class="year">
                  Augut 2010 – May 2014
                </p>
              </div>
            </a>
          </li>
        </ul>
      </div>
      <!-- end .flex-content-->
    </div>
    <!-- .end card-50 -->
  </div>
  <!-- .end .wrap -->
</section>

// src/pages/Resume.tsx
interface ResumeData {
  companies: Company[];
}

interface Company {
  name: string;
  location: string;
  roles: Role[];
}

interface Role {
  title: string;
  start: string;
  end: string;
  projects: Project[];
}

interface Project {
  name?: string;
  description: string;
  techStack: string;
  bullets: string[];
}

const Resume = () => {
  const resumeData: ResumeData = {
    companies: [
      {
        name: 'PwC',
        location: 'Dallas, TX',
        roles: [
          {
            title: 'Senior Software Engineer | Manager',
            start: 'June 2021',
            end: 'Present',
            projects: [
              {
                description:
                  'I am leading software engineers to design and develop new features for an AI-driven, voice enabled, virtual assistant. The application currently exceeds 40,000 unique users a day and has thousands of utterances. It is a critical application at PwC that supports return to office, workplace reservations and time entry among many other features.',
                techStack: 'Angular 12, Ionic 5, Node.js microservices',
                bullets: [
                  'One initiative I led development on was to incorporate the concept of favoriting. We started with favoriting contacts but this component is designed to be generic and can be applied to other pieces.',
                  'Led UI design and development under a very short and strict deadline to accommodate tracking of vaccination status of PwC employees. I created a new site for administrators to view COVID-19 vaccination cards and approve, request additional information or reject employee vaccination status.',
                ],
              },
            ],
          },
          {
            title: 'Software Engineer | Senior Associate',
            start: 'January 2020',
            end: 'June 2021',
            projects: [
              {
                description: `The goal of this project was to develop a proof of concept Angular web application that encapsulates a legacy application using the “strangler” pattern. This successfully proved our ability to have a hybrid legacy / modern web application that can slowly transition to a full rewrite of the web application using modern web frameworks.`,
                techStack: 'Angular 11, Nest.js, .NET Core',
                bullets: [
                  'Modified existing legacy web application to work effectively and efficiently as a standalone web app as well as within an Angular web app using an iframe.',
                  'Developed a solution to handle routing between legacy routes within the iframe and the modern Angular web app.',
                  'Occasionally assisted team as needed in developing .NET Core REST APIs.',
                ],
              },
              {
                description: `I was tasked with developing an advanced automated testing framework that was designed to be a robust solution for testing all JavaScript and TypeScript web and mobile applications at PwC.`,
                techStack: 'Node.js, TypeScript, Selenium, Mocha',
                bullets: [
                  'Initially the goal was to develop automated test cases for a web app named Phoenix using a new, automated testing application developed for PwC by a third party contractor. However, it was quickly realized that it had significant issues and management determined it would be worthwhile to consider alternatives.',
                  'Researched and developed an automated testing framework using Node.js, TypeScript, Selenium, Mocha and other technologies that proved to be far more stable and performant than the previous framework and other solutions.',
                  'Led discussions for proving the value of my approach to management and teammates and gained approval which transitioned stages from R&D to a production application.',
                ],
              },
            ],
          },
        ],
      },
      {
        name: 'Pariveda Solutions',
        location: 'Dallas, TX',
        roles: [
          {
            title: 'Software Engineering Consultant',
            start: 'July 2018',
            end: 'January 2020',
            projects: [
              {
                description:
                  'I was a full stack development consultant for a leading electric utility. The purpose of this project was for key stakeholders up to the CIO to have visibility into the status of business-critical applications especially during unplanned outages.',
                techStack:
                  'Angular v6 with Ionic 4 (mobile app), Node.js API, Express, Angular v8 (web app)',
                bullets: [
                  'Initial scope of the project was limited to front-end development as the Node.js API would be developed by another team. However, our team’s velocity exceeded expectations for speed and quality so our client allowed us to complete API development tasks.',
                  'I worked with the team to refactor and improve the code quality and performance as well as teaching best practices for RESTful APIs.',
                  'Improved my ability to design and develop aesthetically intuitive and pleasing components of the application as we not only wanted to provide an incredibly useful but also usable application.',
                ],
              },
              {
                description:
                  'This application was a multi-year, multi-million-dollar investment by the client to improve many aspects of the business.',
                techStack:
                  'JavaScript front-end that utilizes the Knockout.js library, Java 8 API, and Microsoft SQL Server',
                bullets: [
                  'Utilized Agile methodologies along with a streamlined DevOps cycle to rapidly provide high-value enhancements post go-live of an enterprise level custom web application.',
                  'Contributed to a team tasked with developing new features one of which was a scheduling module that was valued to have over a $1 million per year return on investment.',
                  'Efficiently and effectively collaborated with many different teams such as business analysts, quality assurance, and subject matter experts to ensure the highest quality product was delivered.',
                ],
              },
            ],
          },
        ],
      },
      {
        name: 'Nucor Corporation',
        location: 'Dallas, TX',
        roles: [
          {
            title: 'Oracle SOA Developer',
            start: 'October 2015',
            end: 'June 2018',
            projects: [
              {
                description:
                  'I was a SOA integrations developer where I had the opportunity to design and develop a brand new application called NextConnect which purpose was to view multiple business documents such as purchase orders, shipment receipts and invoices.',
                techStack:
                  'Angular v2-5, Node.js, HTML5, CSS3, Sass, Material Design and RESTful APIs',
                bullets: [
                  'Frequently was tasked with developing solutions to complex and unique problems such as how to get real-time data from various different machines into Oracle E-Business Suite (EBS).',
                  'Responsible for secured file transmissions to and from multiple bank trading partners using FTPS with SSL certificates as well as SFTP and SSH key authentication where yearly total bank transfers would exceed $2 billion.',
                  'Exercised principles of the software development lifecycle (SDLC), Agile and Kanban methodologies with a large, diverse development team to ensure software applications were delivered within project scope, budget and timeline.',
                ],
              },
            ],
          },
        ],
      },
    ],
  };

  return (
    <section
      id="resume"
      className="max-w-screen-md min-h-screen mx-auto text-white"
    >
      <h1 className="p-4 text-3xl font-extrabold text-indigo-200 sm:text-5xl">
        Résumé
      </h1>

      <div className="px-4 divide-y-2 divide-indigo-300">
        {resumeData.companies.map((company: Company, index: number) => {
          return (
            <details key={index} className="py-4 group" open={index === 0}>
              <summary className="flex items-center justify-between cursor-pointer">
                <div className="flex flex-col justify-between w-full lg:flex-row">
                  <div className="lg:flex lg:flex-col lg:justify-evenly">
                    <h1 className="text-2xl font-medium">{company.name}</h1>
                    <h2 className="text-lg font-medium">
                      {company.roles[0].title}
                    </h2>
                  </div>
                  <div className="flex flex-row-reverse items-end justify-between lg:flex-col lg:justify-evenly">
                    <p>{company.location}</p>
                    <p>
                      {company.roles[0].start} – {company.roles[0].end}
                    </p>
                  </div>
                </div>

                <span className="relative ml-1.5 h-5 w-5 flex-shrink-0">
                  <div className="w-5 h-5 text-base">
                    <div className="relative w-5 h-5 border border-white rounded-full">
                      <div className="absolute left-1/2 top-1/2 -ml-1.5 -mt-[1px] h-0.5 w-3 rotate-0 transform bg-white transition-all duration-500 ease-in-out group-open:rotate-180  group-open:transform group-open:transition-all group-open:duration-500 group-open:ease-in-out"></div>
                      <div className="absolute left-1/2 top-1/2 -ml-[1px] -mt-1.5 h-3 w-0.5 rotate-0 transform bg-white opacity-100 transition-all duration-500  ease-in-out group-open:rotate-180  group-open:transform group-open:opacity-0 group-open:transition-all group-open:duration-500 group-open:ease-in-out"></div>
                    </div>
                  </div>
                </span>
              </summary>

              {company.roles.map((role: Role, roleIndex: number) => {
                return (
                  <div key={roleIndex} className="pt-6">
                    {roleIndex > 0 && (
                      <div>
                        <h2 className="text-lg font-medium">
                          {company.roles[roleIndex].title}
                        </h2>
                        <p>
                          {company.roles[roleIndex].start} –
                          {company.roles[roleIndex].end}
                        </p>
                      </div>
                    )}

                    {role.projects.map(
                      (project: Project, projectIndex: number) => {
                        return (
                          <div key={projectIndex}>
                            <p className="pt-4 leading-relaxed">
                              {role.projects.length > 1 && (
                                <b>
                                  Project {role.projects.length - projectIndex}{' '}
                                  -{' '}
                                </b>
                              )}
                              {project.description}
                            </p>
                            <p className="pt-2 leading-relaxed">
                              <b>Tech Stack - </b>
                              {project.techStack}
                            </p>
                            <ul className="pt-4 pl-8 list-disc">
                              {project.bullets.map(
                                (bullet: string, bulletIndex: number) => {
                                  return <li key={bulletIndex}>{bullet}</li>;
                                }
                              )}
                            </ul>
                          </div>
                        );
                      }
                    )}
                  </div>
                );
              })}
            </details>
          );
        })}
      </div>
    </section>
  );
};

export default Resume;
